name = "brimtech-controller"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"

# D1 database
[[d1_databases]]
binding = "DB"
database_name = "brimtech_controller"
database_id = "2bdbc6cb-aca6-40a8-9e0c-76945d1be2ba"

[vars]
TOKEN = "BtC_92fA7xP14_QmZ87Lw3vS4nHk"
